"""ZeroModel perception public API."""

from __future__ import annotations

from .dataset import (
    DATASET_MANIFEST_VERSION,
    INTERACTION_VERSION,
    SPLIT_ASSIGNMENT_VERSION,
    DatasetFindingDTO,
    InMemoryPerceptionDatasetStore,
    PerceptionDatasetError,
    PerceptionDatasetManifestDTO,
    PerceptionDatasetStore,
    RecordedInteractionDTO,
    SplitAssignmentDTO,
    build_dataset_manifest,
)
from .evidence import (
    EVIDENCE_RENDER_SEMANTICS,
    EVIDENCE_VPM_VERSION,
    FIELD_RELEVANCE_SEMANTICS,
    FIELD_RELEVANCE_VERSION,
    EvidenceVPMDTO,
    FieldRelevanceDTO,
    PerceptionEvidenceError,
    estimate_field_relevance,
)
from .fields import (
    FIELD_SAMPLE_VERSION,
    FIELD_SCHEMA_VERSION,
    ExtractedFieldDTO,
    PerceptionFieldError,
    VPMFieldAddressDTO,
    VPMFieldSchemaDTO,
    build_grid_field_schema,
    extract_source_fields,
    mask_source_fields,
    reconstruct_source_array,
    validate_source_for_schema,
)
from .inference import (
    BASELINE_MODEL_VERSION,
    CONFIDENCE_SEMANTICS,
    DISTANCE_SEMANTICS,
    PREDICTION_VERSION,
    ActionCandidateDTO,
    BaselineInferenceConfigDTO,
    BaselineNearestNeighborModelDTO,
    BaselinePredictionDTO,
    BaselineTrainingExampleDTO,
    NeighborEvidenceDTO,
    PerceptionInferenceError,
    fit_baseline_nearest_neighbor,
    predict_baseline_action,
)
from .representation import (
    ACTION_SCHEMA_VERSION,
    SOURCE_ENCODER_VERSION,
    TARGET_ENCODER_VERSION,
    DiscreteActionSchemaDTO,
    PerceptionRepresentationError,
    SourceImageEncoderSpecDTO,
    SourceVPMDTO,
    TargetVPMDTO,
    decode_discrete_action,
    encode_discrete_action,
    encode_source_array,
    encode_source_image_bytes,
)

PERCEPTION_PACKAGE_VERSION = "1.0.13"
PERCEPTION_STAGE = "P4B"

__all__ = [
    "ACTION_SCHEMA_VERSION",
    "BASELINE_MODEL_VERSION",
    "CONFIDENCE_SEMANTICS",
    "DATASET_MANIFEST_VERSION",
    "DISTANCE_SEMANTICS",
    "EVIDENCE_RENDER_SEMANTICS",
    "EVIDENCE_VPM_VERSION",
    "FIELD_RELEVANCE_SEMANTICS",
    "FIELD_RELEVANCE_VERSION",
    "FIELD_SAMPLE_VERSION",
    "FIELD_SCHEMA_VERSION",
    "INTERACTION_VERSION",
    "PERCEPTION_PACKAGE_VERSION",
    "PERCEPTION_STAGE",
    "PREDICTION_VERSION",
    "SOURCE_ENCODER_VERSION",
    "SPLIT_ASSIGNMENT_VERSION",
    "TARGET_ENCODER_VERSION",
    "ActionCandidateDTO",
    "BaselineInferenceConfigDTO",
    "BaselineNearestNeighborModelDTO",
    "BaselinePredictionDTO",
    "BaselineTrainingExampleDTO",
    "DatasetFindingDTO",
    "DiscreteActionSchemaDTO",
    "EvidenceVPMDTO",
    "ExtractedFieldDTO",
    "FieldRelevanceDTO",
    "InMemoryPerceptionDatasetStore",
    "NeighborEvidenceDTO",
    "PerceptionDatasetError",
    "PerceptionDatasetManifestDTO",
    "PerceptionDatasetStore",
    "PerceptionEvidenceError",
    "PerceptionFieldError",
    "PerceptionInferenceError",
    "PerceptionRepresentationError",
    "RecordedInteractionDTO",
    "SourceImageEncoderSpecDTO",
    "SourceVPMDTO",
    "SplitAssignmentDTO",
    "TargetVPMDTO",
    "VPMFieldAddressDTO",
    "VPMFieldSchemaDTO",
    "build_dataset_manifest",
    "build_grid_field_schema",
    "decode_discrete_action",
    "encode_discrete_action",
    "encode_source_array",
    "encode_source_image_bytes",
    "estimate_field_relevance",
    "extract_source_fields",
    "fit_baseline_nearest_neighbor",
    "mask_source_fields",
    "predict_baseline_action",
    "reconstruct_source_array",
    "validate_source_for_schema",
]
