"""ZeroModel Observer demonstration public API.

This package owns bounded Observer-level DTOs for transition comparison,
contradiction artifacts, and replacement lineage. It is a consumer package and
does not widen the core VPM artifact contract.
"""

from zeromodel.observer.artifacts import (
    ObserverContradictionArtifactDTO,
    ObserverFeatureDefinitionDTO,
    ObserverObservationArtifactDTO,
    ObserverObservationSchemaDTO,
    ObserverReplacementPolicyArtifactDTO,
    ObserverTransitionRecordDTO,
    build_contradiction_artifact,
    build_replacement_policy_artifact,
    build_transition_record,
)
from zeromodel.observer.comparison import (
    ObserverComparisonRecipeDTO,
    ObserverComparisonResultDTO,
    ObserverFeatureComparisonDTO,
    ObserverFeatureComparisonResultDTO,
    ObserverHiddenStateHypothesisDTO,
    ObserverHiddenStateHypothesisSetDTO,
    ObserverPolicyConsequenceEvidenceDTO,
    compare_observer_transition,
)
from zeromodel.observer.fixture import (
    ObserverExecutedFixtureStepDTO,
    ObserverFixtureActionDTO,
    ObserverFixtureError,
    ObserverFixtureRuleSetDTO,
    ObserverFixtureStateDTO,
)
from zeromodel.observer.fixture_predictor import (
    ObserverPredictedTransitionDTO,
    build_observer_fixture_comparison_recipe,
    build_observer_fixture_observation_schema,
    execute_observer_fixture_step,
    predict_observer_fixture_transition,
)
from zeromodel.observer.fixture_runtime import (
    ObserverFixtureEpisodeResultDTO,
    ObserverFixtureRuleScheduleEntryDTO,
    active_rule_for_step,
    run_observer_fixture_episode,
)
from zeromodel.observer.graph import (
    ObserverGraphRebuildVerificationDTO,
    ObserverObservationGraphBuildDTO,
    ObserverObservationGraphDTO,
    ObserverObservationGraphEdgeDTO,
    ObserverObservationGraphNodeDTO,
    ObserverStateTransitionKeyDTO,
)
from zeromodel.observer.graph_service import (
    build_observer_observation_graph,
    verify_observer_graph_rebuild,
)
from zeromodel.observer.grouping import (
    ObserverCategoryMappingDTO,
    ObserverGroupedFeatureValueDTO,
    ObserverGroupingFeatureDTO,
    ObserverObservationGraphError,
    ObserverStateClassAssignmentDTO,
    ObserverStateClassDTO,
    ObserverStateGroupingRecipeDTO,
    assign_observation_to_state_class,
)
from zeromodel.observer.habit import (
    ObserverHabitCompilationRecipeDTO,
    ObserverHabitCompilationResultDTO,
    ObserverHabitCounterexampleCoverageDTO,
    ObserverHabitCounterexampleDTO,
    ObserverHabitError,
    ObserverHabitEvaluationDTO,
    ObserverHabitGuardDTO,
    ObserverHabitGuardEvaluationDTO,
    ObserverHabitShadowAuditDTO,
    ObserverHabitShadowAuditRecipeDTO,
    ObserverHabitShadowEpisodeDTO,
    ObserverHabitShadowOccurrenceDTO,
    ObserverHabitShadowReplayDTO,
    ObserverHabitSpecificationDTO,
)
from zeromodel.observer.habit_active_runtime import (
    ObserverActiveHabitExecutionReportDTO,
    ObserverActiveHabitOccurrenceDTO,
    ObserverHabitRuntimeSafetyRecipeDTO,
    run_observer_fixture_with_active_habit,
)
from zeromodel.observer.habit_activation import (
    ObserverActiveHabitDecisionDTO,
    ObserverHabitActivationRequestDTO,
    ObserverHabitActivationResultDTO,
    ObserverHabitActivationScopeDTO,
    activate_observer_habit,
    select_observer_active_action,
)
from zeromodel.observer.habit_admission import (
    ObserverHabitAdmissionDecisionDTO,
    ObserverHabitAdmissionRecipeDTO,
    admit_observer_habit,
)
from zeromodel.observer.habit_registry import (
    InMemoryObserverHabitRegistry,
    ObserverHabitRegistryEntryDTO,
    ObserverHabitRegistryError,
    ObserverHabitRegistryEventDTO,
    ObserverHabitRegistryReplayDTO,
    ObserverHabitRegistrySnapshotDTO,
    ObserverHabitRollbackRequestDTO,
    ObserverHabitRollbackResultDTO,
    empty_observer_habit_registry_snapshot,
    replay_observer_habit_registry,
)
from zeromodel.observer.habit_registry_sqlite import (
    SqliteObserverHabitRegistry,
    SqliteObserverHabitRegistryStore,
)
from zeromodel.observer.habit_registry_store import (
    ObserverHabitRegistryRecoveryDTO,
    ObserverHabitRegistryStore,
    ObserverHabitRegistryStoreCommitDTO,
    ObserverHabitRegistryStoreError,
    ObserverHabitRegistryStoreVerificationDTO,
)
from zeromodel.observer.habit_service import (
    compile_observer_habit_specification,
    evaluate_observer_habit,
)
from zeromodel.observer.habit_shadow import (
    audit_observer_habit_shadow,
    evaluate_observer_habit_over_ledger,
    run_observer_fixture_habit_shadow_episode,
)
from zeromodel.observer.ledger import (
    InMemoryObserverTransitionLedger,
    ObserverLedgerReplayResultDTO,
    ObserverTransitionLedgerEntryDTO,
    ObserverTransitionLedgerSnapshotDTO,
    build_observer_transition_ledger_snapshot,
    replay_observer_fixture_ledger,
    verify_observer_transition_ledger_integrity,
)
from zeromodel.observer.promotion import (
    ObserverEvidenceIndependenceDTO,
    ObserverNoveltyEvidenceDTO,
    ObserverPromotionAnalysisDTO,
    ObserverPromotionAnalysisError,
    ObserverPromotionCandidateDTO,
    ObserverPromotionEvidenceRecipeDTO,
    ObserverRuleChangeSurvivalDTO,
    ObserverRuleChangeTestDTO,
    ObserverRuleRegimeDTO,
    ObserverTransitionOccurrenceDTO,
    ObserverTransitionRecurrenceDTO,
    ObserverTransitionStabilityDTO,
)
from zeromodel.observer.promotion_service import analyze_observer_promotion_candidates
from zeromodel.observer.repair import (
    ObserverProposedChangeDTO,
    ObserverRepairConstraintDTO,
    ObserverRepairProposalDTO,
    ObserverRepairProposalError,
)
from zeromodel.observer.repair_service import propose_observer_repair
from zeromodel.observer.transition_service import (
    ObserverTransitionVerificationDTO,
    ObserverTransitionVerificationError,
    verify_observer_transition,
)
from zeromodel.observer.wake import (
    ObserverWakeEvaluationDTO,
    ObserverWakePolicyAblationDTO,
    ObserverWakePolicyDTO,
    ObserverWakePolicyReplayDTO,
    build_wake_policy_ablation,
    evaluate_wake_policy_for_entry,
    evaluate_wake_policy_over_ledger,
)

__all__ = [
    "ObserverComparisonRecipeDTO",
    "ObserverActiveHabitDecisionDTO",
    "ObserverActiveHabitExecutionReportDTO",
    "ObserverActiveHabitOccurrenceDTO",
    "ObserverComparisonResultDTO",
    "ObserverContradictionArtifactDTO",
    "ObserverExecutedFixtureStepDTO",
    "ObserverEvidenceIndependenceDTO",
    "ObserverFeatureComparisonDTO",
    "ObserverFeatureComparisonResultDTO",
    "ObserverFeatureDefinitionDTO",
    "ObserverFixtureActionDTO",
    "ObserverFixtureEpisodeResultDTO",
    "ObserverFixtureError",
    "ObserverFixtureRuleScheduleEntryDTO",
    "ObserverFixtureRuleSetDTO",
    "ObserverFixtureStateDTO",
    "ObserverGraphRebuildVerificationDTO",
    "ObserverGroupedFeatureValueDTO",
    "ObserverGroupingFeatureDTO",
    "ObserverHabitCompilationRecipeDTO",
    "ObserverHabitCompilationResultDTO",
    "ObserverHabitCounterexampleCoverageDTO",
    "ObserverHabitCounterexampleDTO",
    "ObserverHabitError",
    "ObserverHabitEvaluationDTO",
    "ObserverHabitGuardDTO",
    "ObserverHabitGuardEvaluationDTO",
    "ObserverHabitAdmissionDecisionDTO",
    "ObserverHabitAdmissionRecipeDTO",
    "ObserverHabitActivationRequestDTO",
    "ObserverHabitActivationResultDTO",
    "ObserverHabitActivationScopeDTO",
    "ObserverHabitRegistryEntryDTO",
    "ObserverHabitRegistryError",
    "ObserverHabitRegistryEventDTO",
    "ObserverHabitRegistryReplayDTO",
    "ObserverHabitRegistrySnapshotDTO",
    "ObserverHabitRegistryRecoveryDTO",
    "ObserverHabitRegistryStore",
    "ObserverHabitRegistryStoreCommitDTO",
    "ObserverHabitRegistryStoreError",
    "ObserverHabitRegistryStoreVerificationDTO",
    "ObserverHabitRollbackRequestDTO",
    "ObserverHabitRollbackResultDTO",
    "ObserverHabitRuntimeSafetyRecipeDTO",
    "ObserverHabitShadowAuditDTO",
    "ObserverHabitShadowAuditRecipeDTO",
    "ObserverHabitShadowEpisodeDTO",
    "ObserverHabitShadowOccurrenceDTO",
    "ObserverHabitShadowReplayDTO",
    "ObserverHabitSpecificationDTO",
    "ObserverHiddenStateHypothesisDTO",
    "ObserverHiddenStateHypothesisSetDTO",
    "ObserverLedgerReplayResultDTO",
    "ObserverNoveltyEvidenceDTO",
    "ObserverObservationGraphBuildDTO",
    "ObserverObservationGraphDTO",
    "ObserverObservationGraphEdgeDTO",
    "ObserverObservationGraphError",
    "ObserverObservationGraphNodeDTO",
    "ObserverObservationArtifactDTO",
    "ObserverObservationSchemaDTO",
    "ObserverPolicyConsequenceEvidenceDTO",
    "ObserverPredictedTransitionDTO",
    "ObserverPromotionAnalysisDTO",
    "ObserverPromotionAnalysisError",
    "ObserverPromotionCandidateDTO",
    "ObserverPromotionEvidenceRecipeDTO",
    "ObserverProposedChangeDTO",
    "ObserverRepairConstraintDTO",
    "ObserverRepairProposalDTO",
    "ObserverRepairProposalError",
    "ObserverReplacementPolicyArtifactDTO",
    "ObserverRuleChangeSurvivalDTO",
    "ObserverRuleChangeTestDTO",
    "ObserverRuleRegimeDTO",
    "ObserverStateClassAssignmentDTO",
    "ObserverStateClassDTO",
    "ObserverStateGroupingRecipeDTO",
    "ObserverStateTransitionKeyDTO",
    "ObserverTransitionLedgerEntryDTO",
    "ObserverTransitionLedgerSnapshotDTO",
    "ObserverTransitionOccurrenceDTO",
    "ObserverTransitionRecurrenceDTO",
    "ObserverTransitionRecordDTO",
    "ObserverTransitionStabilityDTO",
    "ObserverTransitionVerificationDTO",
    "ObserverTransitionVerificationError",
    "ObserverWakeEvaluationDTO",
    "ObserverWakePolicyAblationDTO",
    "ObserverWakePolicyDTO",
    "ObserverWakePolicyReplayDTO",
    "InMemoryObserverTransitionLedger",
    "InMemoryObserverHabitRegistry",
    "SqliteObserverHabitRegistry",
    "SqliteObserverHabitRegistryStore",
    "ObserverCategoryMappingDTO",
    "build_contradiction_artifact",
    "build_observer_observation_graph",
    "build_observer_fixture_comparison_recipe",
    "build_observer_fixture_observation_schema",
    "build_observer_transition_ledger_snapshot",
    "build_replacement_policy_artifact",
    "build_transition_record",
    "build_wake_policy_ablation",
    "compare_observer_transition",
    "assign_observation_to_state_class",
    "evaluate_wake_policy_for_entry",
    "evaluate_wake_policy_over_ledger",
    "execute_observer_fixture_step",
    "predict_observer_fixture_transition",
    "propose_observer_repair",
    "replay_observer_fixture_ledger",
    "run_observer_fixture_episode",
    "verify_observer_transition",
    "verify_observer_graph_rebuild",
    "verify_observer_transition_ledger_integrity",
    "active_rule_for_step",
    "analyze_observer_promotion_candidates",
    "admit_observer_habit",
    "activate_observer_habit",
    "audit_observer_habit_shadow",
    "compile_observer_habit_specification",
    "evaluate_observer_habit",
    "evaluate_observer_habit_over_ledger",
    "empty_observer_habit_registry_snapshot",
    "replay_observer_habit_registry",
    "run_observer_fixture_habit_shadow_episode",
    "run_observer_fixture_with_active_habit",
    "select_observer_active_action",
]
