"""Dependency-free Lua export for compiled ZeroModel policy consumers."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Mapping

from zeromodel.core.policy_lookup import VPMPolicyLookup

POLICY_LUA_FORMAT = "zeromodel-lua-policy/v1"


def _canonical_json_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")


def compiled_plan_id(plan: Mapping[str, Any]) -> str:
    """Return a deterministic identity for one consumer execution plan."""
    return hashlib.sha256(_canonical_json_bytes(dict(plan))).hexdigest()


def _lua_string(value: str) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def _lua_number(value: float) -> str:
    number = float(value)
    if number == 0.0:
        return "0.0"
    return repr(number)


def _lua_string_array(values: list[str]) -> str:
    return "{" + ", ".join(_lua_string(value) for value in values) + "}"


def _lua_int_array(values: list[int]) -> str:
    return "{" + ", ".join(str(int(value)) for value in values) + "}"


def _lua_number_array(values: list[float]) -> str:
    return "{" + ", ".join(_lua_number(value) for value in values) + "}"


def lua_policy_source(reader: VPMPolicyLookup) -> str:
    """Compile ``reader`` into a dependency-free Lua policy module.

    The Lua module retains the exact VPM ``artifact_id`` and a separate
    deterministic ``plan_id`` for the reader configuration. It provides a small
    ``choose(row_id)`` hot path and a trace-rich ``read(row_id)`` function.
    """
    plan = reader.to_compiled_plan()
    plan_id = compiled_plan_id(plan)

    lines = [
        "-- Generated by ZeroModel. Do not edit by hand.",
        "-- The artifact_id identifies the immutable VPM policy artifact.",
        "-- The plan_id identifies this exported consumer configuration.",
        "local policy = {",
        "  format = %s," % _lua_string(POLICY_LUA_FORMAT),
        "  artifact_id = %s," % _lua_string(str(plan["artifact_id"])),
        "  plan_id = %s," % _lua_string(plan_id),
        "  value_source = %s," % _lua_string(str(plan["value_source"])),
        "  evidence_value_source = %s,"
        % _lua_string(str(plan["evidence_value_source"])),
        "  tie_break = %s," % _lua_string(str(plan["tie_break"])),
        "  actions = %s," % _lua_string_array(list(plan["action_metric_ids"])),
        "  evidence_metrics = %s,"
        % _lua_string_array(list(plan["evidence_metric_ids"])),
        "  action_source_metric_indices = %s,"
        % _lua_int_array(list(plan["action_source_metric_indices"])),
        "  action_view_columns = %s,"
        % _lua_int_array(list(plan["action_view_columns"])),
        "  rows = {",
    ]

    for source_row, row_id in enumerate(plan["row_ids"]):
        winner = int(plan["winner_indices"][source_row])
        lines.extend(
            [
                "    [%s] = {" % _lua_string(str(row_id)),
                "      winner = %d," % (winner + 1),
                "      source_row_index = %d," % source_row,
                "      view_row = %d,"
                % int(plan["source_to_view_rows"][source_row]),
                "      values = %s,"
                % _lua_number_array(list(plan["action_values"][source_row])),
                "      evidence = %s,"
                % _lua_number_array(list(plan["evidence_values"][source_row])),
                "    },",
            ]
        )

    lines.extend(
        [
            "  },",
            "}",
            "",
            "local function resolve(row_id)",
            "  local row = policy.rows[row_id]",
            "  if row == nil then",
            "    error(\"Unknown policy row_id: \" .. tostring(row_id), 3)",
            "  end",
            "  return row",
            "end",
            "",
            "function policy.choose(row_id)",
            "  local row = resolve(row_id)",
            "  return policy.actions[row.winner]",
            "end",
            "",
            "function policy.choose_many(row_ids)",
            "  local actions = {}",
            "  for index, row_id in ipairs(row_ids) do",
            "    actions[index] = policy.choose(row_id)",
            "  end",
            "  return actions",
            "end",
            "",
            "function policy.read(row_id)",
            "  local row = resolve(row_id)",
            "  local winner = row.winner",
            "  local candidates = {}",
            "  for index, action in ipairs(policy.actions) do",
            "    candidates[action] = row.values[index]",
            "  end",
            "  local evidence = {}",
            "  for index, metric in ipairs(policy.evidence_metrics) do",
            "    evidence[metric] = row.evidence[index]",
            "  end",
            "  return {",
            "    artifact_id = policy.artifact_id,",
            "    plan_id = policy.plan_id,",
            "    row_id = row_id,",
            "    action = policy.actions[winner],",
            "    metric_id = policy.actions[winner],",
            "    value = row.values[winner],",
            "    source_row_index = row.source_row_index,",
            "    source_metric_index = policy.action_source_metric_indices[winner],",
            "    view_row = row.view_row,",
            "    view_column = policy.action_view_columns[winner],",
            "    candidates = candidates,",
            "    evidence = evidence,",
            "  }",
            "end",
            "",
            "return policy",
            "",
        ]
    )
    return "\n".join(lines)


def write_lua_policy(
    reader: VPMPolicyLookup,
    path: str | Path,
) -> Path:
    """Write a deterministic Lua module for ``reader`` and return its path."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(lua_policy_source(reader), encoding="utf-8")
    return target
